version: '2'
services:
  rabbit:
    build:
      context: ./rabbit
      dockerfile: Dockerfile
    restart: always
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./docker_data/rabbitmq:/var/lib/rabbitmq
    ports:
      - 5671:5671
    hostname: rabbit
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - ./docker_data/mongo:/data/db
    logging:
      driver: none
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - 127.0.0.1:28000:80
    links:
      - rabbit
      - mongo
    depends_on:
      - rabbit
      - mongo
    environment:
      - INIT_USERNAME=admin
      - INIT_PASSWORD=admin_pass
      - SYSTEM_PASSWORD=${SYSTEM_PASSWORD}
  monitor:
    build:
      context: ./monitor
      dockerfile: Dockerfile
    restart: always
    links:
      - rabbit
      - mongo
    depends_on:
      - rabbit
      - mongo
    environment:
      - SYSTEM_PASSWORD=${SYSTEM_PASSWORD}
  beat:
    build:
      context: ./beat
      dockerfile: Dockerfile
    restart: always
    links:
      - rabbit
      - mongo
    depends_on:
      - rabbit
      - mongo
    environment:
      - SYSTEM_PASSWORD=${SYSTEM_PASSWORD}
  flower:
    image: totem/celery-flower-docker
    ports:
      - 0.0.0.0:5555:172.17.42.1:5555
    links:
      - rabbit
    depends_on:
      - rabbit
    environment:
      - AMQP_USERNAME=system
      - AMQP_PASSWORD=${SYSTEM_PASSWORD}
      - AMQP_HOST=rabbit
      - FLOWER_BASIC_AUTH=admin:admin_pass

